ログイン機能
kunikida007/tw pull request #1
Opened 2021-05-26 07:59 UTC by kunikida007

ログイン機能、登録機能を実装させていただきました。
twiterに関するファイルは今回の機能には関連致しません。
お手数をおかけいたしますが、ご確認お願いいたします。

2021-05-27 07:03 UTC, s-nakajima2 reviewed
きちんと動いているようです。
いくつかの点をコメントしたので確認してください。

2021-05-27 12:38 UTC, kunikida007 commented on config/settings.py
> +LOGOUT_REDIRECT_URL='/login'
レビューありがとうございます。
ただいま拝見させて頂きました。
templates/twiterに関するファイルは今回の機能には関係なく、
私のミスでaddしてしまったのでスルーして頂ければ幸いです。
お手数をおかけいたしますが、引き続き宜しくお願い致します。

2021-05-27 13:52 UTC, s-nakajima2 requested changes
お疲れ様です。前回のレビューの修正内容にはおおむね問題ありません。次の項目を確認してください：
- 前回のレビューに書いたファイル末尾の改行をもう一度確認してみてください(twiterの方のファイルの中にもあるのであらかじめ直しておいた方が良いかと思います)。
- `.gitignore`を追加してください。`db.sqlite3`や`__pychache__`、仮想環境のフォルダをgitの管理から除外することはお互いのために役立ちます。DjangoGirlsチュートリアル[https://tutorial.djangogirls.org/ja/deploy/](url)の`.gitignore`の内容が参考になるかと思います。なお、あとから`.gitignore`を反映させる方法は調べてみてください。

2021-05-27 13:52 UTC, s-nakajima2 commented on config/settings.py
> +LOGOUT_REDIRECT_URL='/login/'
```suggestion
LOGOUT_REDIRECT_URL='/login/' 

```

2021-05-29 00:52 UTC, s-nakajima2 commented on .gitignore
> +x
このファイルは既にコミットしたものに対しては適用されません。（[https://qiita.com/anqooqie/items/110957797b3d5280c44f#gitignore%E3%81%AB%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%82%92%E8%BF%BD%E5%8A%A0%E3%81%97%E3%81%9F%E3%81%AE%E3%81%AB%E7%84%A1%E8%A6%96%E3%81%95%E3%82%8C%E3%81%AA%E3%81%84](url)）そのため、別の方法を使って適用させる必要があります。次にファイルを足すとき、gitの管理がいらないものがあれば先に.gitignoreファイルに書いておくことをお勧めします。

2021-05-29 00:53 UTC, s-nakajima2 reviewed
お疲れ様です。
コメントしたのでご確認ください。

2021-05-29 07:42 UTC, s-nakajima2 reviewed
LGTM(Looks Good To Me). 二次レビューにお渡しします。
以下はすぐに直す必要はないです。気になったポイントを挙げておくので今後の役に立てば幸いです。
- DjangoではデフォルトのUser(`from django.contrib.auth.models import User`)は利用しない方がいいとされているようです。次にDjangoで何か作る時は、`AbstractUser`や`AbstractBaseUser`を継承したカスタムユーザーモデルを使ってみましょう。
- もう少し細かくコミットしてもいいかもしれません（１ファイルを直して正常に動いたところでコミットする…など）。これは好みによるのでしっくりくるやり方を探してみてください。

2021-05-29 11:10 UTC, Akinori13 requested changes
いくつかコメントしました。
- `.gitignore`が見当たらないので追加しておいてください。
- テストを書いてみましょう。（最初は難しいと思いますが、ステータスコードやテンプレートが適切かなどのテストから書いてみてください。）

2021-05-29 11:10 UTC, Akinori13 commented on user/forms.py
> +
SignUpFormは`django.contrib.auth.forms`から`UserCreationForm`を継承する方が良いと思います。数字だけのパスワードや一般的なパスワード、推測される可能性のあるパスワードを`UserCreationForm`がチェックしてくれるからです。さらに文字数などのヴァリデーションをカスタマイズしたい場合は、上書きしてみましょう。

2021-05-29 11:10 UTC, Akinori13 commented on user/urls.py
> +    path('', auth_views.LoginView.as_view(template_name="user/login.html"), name='login'),
loginのPathは`login/`とかの方がいいと思います。

2021-05-29 11:10 UTC, Akinori13 commented on config/settings.py
> +LOGOUT_REDIRECT_URL='/login/'
最終行に空行を挿入してください。

2021-06-01 10:37 UTC, Akinori13 requested changes
いくつかこめんとしました。

2021-06-01 10:37 UTC, Akinori13 commented on user/tests.py
> +
テストをはじめから書くのは難しいと思いますが、下記の点に目を通してもう一度書いてください。
### テストの実行方法
テストの実行方法は、`python manage.py test`です。提出前に必ず実行して確認してください。
### テストの書き方
テストの書き方は非常に多くありますが、ユーザーの行動に合わせて（すなわちViewに合わせる。）書くのがベターであると思います。以下の例は以前書いたテストの一部です。ユーザー登録機能ではありませんが、参考にしてください。また( https://github.com/django/django/blob/main/tests/auth_tests/test_views.py#L100 )はdjangoのテストです。どちらを参考にしても構いません。
```python
class TestSpeakDeleteView(TestCase): # ツイート削除機能
    def setUp(self):
        self.user = User.objects.create_user(
            username='test_user1', 
            email='test_email1@user.com',
            password='test_password1',
        )
        self.client.force_login(self.user)

    ```
   以下共通の処理
    ```
    def create_speak(self, content: str): 
        self.speak = Speak.objects.create(
            content=content,
            user=self.user
        )
        return self.speak

    def get(self, pk: int):
        return self.client.get(reverse('speaks:speak_delete', args=[pk]))
    
    def post(self, pk: int, post_data={}):
        return self.client.post(reverse('speaks:speak_delete', args=[pk]), post_data)

    ```
   以下テスト
   フォームを使う場合は一つのviewは、さらにgetとpostに分けられることがある。その場合は、先にいずれかのテストを終えてしまう。
    ```
    def test_get_succeeds(self): # できることを確認するテストの場合は「succeeds」をつける。
        speak = self.create_speak(content='test_get_succeeds')

        response = self.get(speak.id)
        self.assertEqual(response.status_code, 200)
        self.assertTemplateUsed(response, 'speaks/speak_delete.html')
    
    def test_get_fails_by_logouted_user(self): # できないことを確認するテストの場合は「fails」をつける。
        speak = self.create_speak(content='test_get_fails_by_logouted_user')
        self.client.logout()
        response = self.get(speak.id)
        params = urlencode({'next':reverse('speaks:speak_delete', args=[speak.id])})
        expected_url = f'{reverse(settings.LOGIN_URL)}?{params}'
        self.assertRedirects(response, expected_url)

    def test_post_succeeds(self):
        speak = self.create_speak(content='test_post_succeeds')

        response = self.post(speak.id)
        self.assertRedirects(response, reverse('accounts:home'))

        self.assertEqual(Speak.objects.filter(content='test_post_succeeds').count(), 0)

    def test_post_fails_by_logouted_user(self):
        speak = self.create_speak(content='test_post_fails_by_logouted_user')

        self.client.logout()
        response = self.post(speak.id)
        params = urlencode({'next':reverse('speaks:speak_delete', args=[speak.id])})
        expected_url = f'{reverse(settings.LOGIN_URL)}?{params}'
        self.assertRedirects(response, expected_url)

        self.assertEqual(Speak.objects.filter(content='test_post_fails_by_logouted_user').count(), 1)
```

2021-06-04 04:54 UTC, Akinori13 requested changes
いくつかコメントしました。
テストは難しく感じていると思いますが、頑張りましょう。

2021-06-04 04:54 UTC, Akinori13 commented on user/urls.py
> +#ログアウト機能は後で実装
`loguout`は未作成なので消しちゃいましょう。余分なコードは入れないのがベターです。

2021-06-04 04:54 UTC, Akinori13 commented on config/settings.py
> +LOGOUT_REDIRECT_URL='/login/'
`loguout`は未作成なので消しちゃいましょう。余分なコードは入れないのがベターです。

2021-06-04 04:54 UTC, Akinori13 commented on user/views.py
> +from django.shortcuts import redirect
使っていないモジュールは消しちゃいましょう。

2021-06-04 04:54 UTC, Akinori13 commented on user/views.py
> +
余分な空白は消してください。

2021-06-04 04:54 UTC, Akinori13 commented on user/views.py
> +            return   render(request, 'user/login.html')
```suggestion
            return render(request, 'user/login.html')
```

2021-06-04 04:54 UTC, Akinori13 commented on config/settings.py
> +LOGOUT_REDIRECT_URL='/login/'
`LOGIN_REDIRECT_URL`は、`/`にするかアカウントページを新規作成してそれを指定しましょう。

2021-06-04 04:54 UTC, Akinori13 commented on user/tests.py
> +
余分な空白は消してください。

2021-06-04 04:54 UTC, Akinori13 commented on user/tests.py
> +class Signin_tests(TestCase):
クラス名の命名規則を[こちら](https://pep8-ja.readthedocs.io/ja/latest/#id24)で確認してください。
`signin`ではなく`login`を使用した方が良いと思います。

2021-06-04 04:54 UTC, Akinori13 commented on user/tests.py
> +class Signup_Tests(TestCase):
クラス名の命名規則を[こちら](https://pep8-ja.readthedocs.io/ja/latest/#id24)で確認してください。

2021-06-04 04:54 UTC, Akinori13 commented on user/tests.py
> +        self.assertTemplateUsed(response, 'user/signup.html')
一つのViewには`get`と`post`があることがあると以前お伝えしました。それによって`class`を分けることは構いませんが、`GET`なのか`POST`なのかを明示した方が良いでしょう。

2021-06-04 04:54 UTC, Akinori13 commented on user/tests.py
> +        self.assertTrue(User.objects.filter(username='new_username').exists())
`POST`しましょう。

2021-06-04 04:54 UTC, Akinori13 commented on user/tests.py
> +        self.assertRedirects(response, reverse('twiter:home'))
```suggestion
        self.assertRedirects(response, reverse(settings.LOGIN_REDIRECT_URL))
```

2021-06-04 11:41 UTC, Akinori13 requested changes
コメントしました。

2021-06-04 11:41 UTC, Akinori13 commented on user/tests.py
> +class  TestUrls(TestCase):
```suggestion
class TestUrls(TestCase):
```

2021-06-04 11:41 UTC, Akinori13 commented on user/tests.py
> +class Test_signup_get_Views(TestCase):
命名規則に従ってください。

2021-06-04 11:41 UTC, Akinori13 commented on user/tests.py
> +from user.forms import SignUpForm
使っていないなら消してください。

2021-06-04 11:41 UTC, Akinori13 commented on user/tests.py
> +class Sigup_post_Tests(TestCase):
命名規則に従ってください。

2021-06-04 11:41 UTC, Akinori13 commented on user/tests.py
> +class Login_tests(TestCase):
命名規則に従ってください。

2021-06-04 11:41 UTC, Akinori13 commented on user/tests.py
> +        self.assertTrue(User.objects.filter(username='new_username').exists())
`POST`してください。（`response = self.client.post`してください。）

2021-06-04 11:41 UTC, Akinori13 commented on user/tests.py
> +        self.assertFalse(form.is_valid())
テストは基本的にユーザーの視点で書きます。https://github.com/kunikida007/tw/pull/1#discussion_r642985151 で伝えた内容を再度確認してください。

2021-06-05 06:11 UTC, kunikida007 commented on user/tests.py
> +class Test_signup_get_Views(TestCase):
「命名規則に従ってください。」というコメントについて添付されたリンクを確認させて頂きましたが、理解することができませんでした。
コメントにあった命名規則とは、1つのテストを通して大文字、小文字の使いかたを統一する。という解釈でよろしいでしょうか？

2021-06-05 06:15 UTC, kunikida007 commented on user/tests.py
> +        self.assertFalse(form.is_valid())
確認させて頂きましたが、ユーザーの行動に合わせて（すなわちViewに合わせる。）という部分がいまいち理解できませんでした。どのようにコード修正を行えばいいか助言をいただけると幸いです。

2021-06-05 11:06 UTC, Akinori13 commented on user/tests.py
> +class Test_signup_get_Views(TestCase):
クラス名のところをみてください。`LoginTest`などとなります。

2021-06-05 12:11 UTC, Akinori13 commented on user/tests.py
> +        self.assertFalse(form.is_valid())
分かりづらい表現で申し訳ないです。

ユーザーが会員登録する行動を思い浮かべてください。
(1)`https://domain/signup`を訪問する。
(2)Formに名前とパスワードを入力して送信し、リダイレクトされる。
の二段階ですが、これらは`SignupView`という一つのViewにより制御されています。ですからある機能のテストを書く時は、まずは`View`に合わせて書くことがベターであると思われます。他方で(1)と(2)の手順はつながっているように見えて、実際は`GET`と`POST`という異なるリクエストをしているわけですから、テストクラスごと分ける場合やテストクラス内で分けることなどが考えられます。

さて、「まずは`View`に合わせて書くことがベターである」と申しましたが、このような結論に私が至っているのは、アプリはユーザの利用を想定しているからです。どれほど`url`が存在していることをチェックしても、どれほど`form`がヴァリデーションをしっかりしているか確認しても、`Signup`ができなければ価値がありません。だから`View`に合わせて書かれたテストは最低限必要なものになります。ですから`client.post()`や`client.get()`などでテストします。ビューレベルのテストが終われば、`Form`や`Model`などのテストを書いてもいいと思います。テストはたくさん書くことが大切ですから。

重ねて「`View`に合わせて書く」の説明をします。先ほど「ある機能のテストを書く時は、」と申しましたが、会員登録機能でテストすべきことは「ユーザーが会員登録できるか」で、非常にシンプルです。ですが、フォロー機能は実際にはフォロー機能とアンフォロー機能を、ツイート機能はツイート作成、閲覧、更新、削除機能にさらに分化します。（もちろん会員登録機能には、パスワードリセット機能、パスワードチェンジ機能、退会機能を含むかもしれません。）
ツイート機能を例にとれば、`TweetTest`クラスの中に大量の`test_~`関数を含むよりも、
- `TweetCreateTest`
- `TweetReadTest`
- `TweetUpdateTest`
- `TweetDeleteTest`

に分けたほうが可読性が高く、発見しやすいでしょう。そして、もし僕がツイート作成、閲覧、更新、削除機能を作るなら、
- `TweetCreateView`
- `TweetReadView`
- `TweetUpdateView`
- `TweetDeleteView`

となります。これはTestと一致しませんか？

これで説明は終わりですが、分からなければどんどん聞いてください。

これは追記ですがテストには、二種類あります。会員登録機能を例にすれば、「会員登録できるか」と「不適切な場合に会員登録できないか」のテストです。後者と前者を分けるために、関数名に`succeeds`や`fails`をつけたり、`~_with_invalid_email`などと書いたりします。

2021-06-06 11:04 UTC, Akinori13 requested changes
いくつかコメントしました。

2021-06-06 11:04 UTC, Akinori13 commented on user/tests.py
> +        self.assertEqual(response.status_code, 404)
もう一つ具体例を書いておきますから、ここ以外も同じように修正してください。。
多少の時間はかかっても構いませんから、[これ](https://github.com/kunikida007/tw/pull/1#discussion_r642985151)のコードをじっくり読んで欲しいです。まずは、まねて書いてください。
```python
def test_post_fails_by_existed_user(self):
    # client.postはこのように使います。
    response = self.client.post(
        reverse('accounts:signup'), 
        {'username': 'username', 'password1': 'password', 'password2': 'password'}
    )
    # ページ遷移が発生していないか。
    self.assertEqual(response.status_code, 200)
    # テンプレートは正しいか。
    self.assertTemplateUsed(response, 'accounts/signup.html')
    # エラーは表示されているか。
    self.assertIn('このユーザーネームは既に使われています', response.context['form'].errors['username'])
    # 本当にユーザーは登録されてないのか。
    self.assertEqual(User.objects.filter(username='username').count(), 1)
```

2021-06-06 11:04 UTC, Akinori13 commented on user/tests.py
> +        self.assertEqual(response.status_code, 404)
ちなみにこの具体例も完全な例ではありません。`password`はありきたりですから、それでもバリデーションエラーが発生しているはずです。
必ず`print(response.context['form'])`などで確認してみましょう。

2021-06-07 06:12 UTC, kunikida007 commented on user/tests.py
> +        self.assertEqual(response.status_code, 404)
確認させて頂きました。

 # エラーは表示されているか。
    self.assertIn('このユーザーネームは既に使われています', response.context['form'].errors['username'])

この部分のテストを実行したところ、

self.assertIn( response.context['form'].errors["username"],'このユーザーネームは既に使われていま 
す')
KeyError: 'username'

のエラーが発生してしまいます。
このERRORを解消する為にいくつか調べて試してみたのですが、解決に至りませんでした。
この事象を解消する為に意見をいただきたいです。

2021-06-07 06:44 UTC, Akinori13 commented on user/tests.py
> +        self.assertEqual(response.status_code, 404)
テストのコードとテスト結果のスクリーンショットを送ってください。

2021-06-08 04:48 UTC, kunikida007 commented on user/tests.py
> +        self.assertEqual(response.status_code, 404)
![screenshot 1](https://user-images.githubusercontent.com/65271579/121124565-1c2c1a00-c860-11eb-896f-acfab8f9f399.jpg)

```

2021-06-08 04:48 UTC, kunikida007 commented on user/tests.py
> +        self.assertEqual(response.status_code, 404)
こちらになります。宜しくお願い致します。

2021-06-08 05:39 UTC, Akinori13 commented on user/tests.py
> +        self.assertEqual(response.status_code, 404)
@kunikida007 
`username`というユーザーがまだ存在しないので、その部分ではエラーが発生していないが、`password`という一般的すぎるパスワードのエラーが発生しているという状況であると思います。
重複するユーザーを用意してみてください。

2021-06-11 09:17 UTC, Akinori13 requested changes
- 使ってないモジュールは読み込まない。（拡張機能を入れる）
- インデントの位置がずれてる。
- [これ](https://pep8-ja.readthedocs.io/ja/latest/) に従う。特にリストのところは複数書き方があるので注意して読む。

2021-06-11 09:17 UTC, Akinori13 commented on user/test.py
> +from django.test import TestCase,Client
```suggestion
from django.test import TestCase, Client
```

2021-06-11 09:17 UTC, Akinori13 commented on user/test.py
> +    )
```suggestion
        response = self.client.post(
            self.index_url, 
            {'username': 'username1', 'password1': 'password', 'password2': 'password'}
        )
```

2021-06-13 13:49 UTC, Akinori13 requested changes
いくつかコメントしました。

2021-06-13 13:49 UTC, Akinori13 commented on user/test.py
> +from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
使ってないモジュールを消してください。

2021-06-13 13:49 UTC, Akinori13 commented on user/test.py
> +from .views import signup
使ってないモジュールを消してください。

2021-06-13 13:49 UTC, Akinori13 commented on user/test.py
> +        self.client = Client()
必要ありません。

2021-06-13 13:49 UTC, Akinori13 commented on user/test.py
> +        # ページ遷移が発生していないか。
これらのコメントはプログラムを見れば理解できるので消しちゃってください。

2021-06-13 13:49 UTC, Akinori13 commented on user/test.py
> +          # ユーザー名は既に存在するのか？
これも消しますが、Pythonではインデントが重要であることを認識してください。

2021-06-13 13:49 UTC, Akinori13 commented on user/test.py
> +         )
インデントの位置

2021-06-13 13:49 UTC, Akinori13 commented on user/test.py
> +    def test_signup_view(self):
名前は`test_get_succeeds`の方が分かりやすいです。

2021-06-13 13:49 UTC, Akinori13 commented on user/test.py
> +    def test_save_user(self):
ここも`test_post_succeds`の方が分かりやすいです。

2021-06-13 13:49 UTC, Akinori13 commented on user/test.py
> +        self.assertEqual(User.objects.filter(username='notexistuser').count(),0)
改行する。

2021-06-13 13:50 UTC, Akinori13 commented on user/test.py
> +        self.assertEqual(User.objects.filter(username='notexistuser').count(),0)
メソッド同士の間に空の行を挿入してください。

2021-06-14 09:46 UTC, kunikida007 commented on user/test.py
> +         )
以前添付して頂いたリンクを参考にインデントの位置を修正させて頂きましたが、どのように修正すればよろしいでしょうか？

2021-06-14 09:53 UTC, Akinori13 commented on user/test.py
> +         )
```suggestion
        )
```

2021-06-21 05:22 UTC, Akinori13 commented on user/test.py
> +from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
```suggestion
from django.contrib.auth.forms import AuthenticationForm
```
使っていないモジュールは消しちゃってください。

2021-06-23 15:33 UTC, Akinori13 requested changes
いくつかコメントしました。インデントの位置とクラス名の命名規則に常に注意を払う必要があります。

2021-06-23 15:33 UTC, Akinori13 commented on user/test.py
> +    def  test_post_fails_by_existed_user(self):
```suggestion
    def test_post_fails_by_existed_user(self):
```

2021-06-23 15:33 UTC, Akinori13 commented on user/test.py
> +class Login_test(TestCase):
命名規則に従ってください。

2021-06-23 15:33 UTC, Akinori13 commented on user/test.py
> +        #フォームが正しくないと認識する
基本的に`#`とコメントの間にスペースを一つ入れる
```suggestion
        # フォームが正しくないと認識する
```

2021-06-23 15:33 UTC, Akinori13 commented on user/test.py
> +         # エラーは表示されているか。
インデントの位置を基本的に合わせる。

2021-06-23 15:33 UTC, Akinori13 commented on user/test.py
> +         # ユーザー名は存在していない。
ここも

2021-06-23 15:33 UTC, Akinori13 commented on user/test.py
> +         #アカウントが作成されているか？
ここも

2021-06-26 13:43 UTC, Akinori13 commented
僕がコメントしたところを修正したかを再度確認してください。もし分かりづらければ質問してください。

2021-06-27 13:00 UTC, kunikida007 commented on user/test.py
> +         # エラーは表示されているか。
インデントの位置を基本的に合わせるとはどういったことでしょうか？

2021-06-27 13:02 UTC, kunikida007 commented on user/test.py
> +         # ユーザー名は存在していない。
#の位置をselfの位置にあわせるということでしょうか？

2021-06-28 07:53 UTC, Akinori13 commented on user/test.py
> +         # ユーザー名は存在していない。
そうです。
[こちら](https://note.nkmk.me/python-comment/)もある程度参考になると思うで確認してください。

2021-06-29 15:16 UTC, Akinori13 requested changes
いくつかコメントしました。

2021-06-29 15:16 UTC, Akinori13 commented on config/urls.py
> +    path('twiter/',include('twiter.urls')),
使わないので削除してください。

2021-06-29 15:16 UTC, Akinori13 commented on config/settings.py
> +    "twiter",
使わないので削除して下さい。

2021-06-30 06:29 UTC, kunikida007 commented on config/urls.py
> +    path('twiter/',include('twiter.urls')),
すでにツイート機能を一部作成しており、その中で使っているのですが、消去はしたほうがよろしいでしょうか？

2021-07-01 12:57 UTC, Akinori13 commented on config/urls.py
> +    path('twiter/',include('twiter.urls')),
まだ必要でないコードを含めないようにしてください。

2021-07-04 04:30 UTC, Akinori13 commented on config/settings.py
> +LOGIN_REDIRECT_URL = 'twiter:home'
変更してください。

2021-07-05 12:09 UTC, Akinori13 commented on config/settings.py
> +LOGIN_REDIRECT_URL = 'twiter:home'
@kunikida007 
変更後はエラーが出ないかテストしてください。

2021-07-05 12:34 UTC, kunikida007 commented on config/settings.py
> +LOGIN_REDIRECT_URL = 'twiter:home'
ログイン、登録機能作成時にLOGIN_REDIRECT_URL先をまだ作成していないため、user/test.pyからリダイレクト先の確認をする項目を消去いたしました。

2021-07-07 12:19 UTC, Akinori13 requested changes
コメントしました。

2021-07-07 12:19 UTC, Akinori13 commented on user/test.py
> +        self.assertEqual(User.objects.filter(username='notexistuser').count(),0)
実際にPOSTしてエラーが表示されるか確認してください。

2021-07-07 12:19 UTC, Akinori13 commented on user/test.py
> +
ここも含めてですが、可読性が下がるので関数内には空行は基本的に必要ないです。削除してください

2021-07-09 05:32 UTC, Akinori13 approved these changes

2021-07-12 07:08 UTC, fumiharun11 requested changes

2021-07-12 07:08 UTC, fumiharun11 commented on user/test.py
> +    def test_post_succeds(self):
`succeds`はスペルミス？

2021-07-12 07:08 UTC, fumiharun11 commented on user/test.py
> +    def test_faild_with_diffrent_password(self):
`faild`はスペルミス？

2021-07-12 07:08 UTC, fumiharun11 commented on user/test.py
> +        self.assertEqual(User.objects.filter(username='username6').count(), 1)
`count()`でチェックしても良いけど`exists()`でチェックするのでも良さそうかな？
参考: https://docs.djangoproject.com/en/3.2/ref/models/querysets/#exists

2021-07-12 12:12 UTC, kunikida007 commented on .gitignore
> +x
仮想環境のファイルです。

2021-07-12 12:53 UTC, kunikida007 commented on user/models.py
> +from django.contrib.auth.models import AbstractUser
ミスです。

2021-07-12 12:53 UTC, kunikida007 commented on config/settings.py
> +        'DIRS': [os.path.join(BASE_DIR, 'templates')],
ミスでした。

2021-07-12 12:59 UTC, kunikida007 commented on user/test.py
> +    def test_faild_with_diffrent_password(self):
スペルミスです。

2021-07-12 12:59 UTC, kunikida007 commented on user/test.py
> +    def test_post_succeds(self):
スペルミスです。

2021-07-15 05:03 UTC, fumiharun11 commented on user/test.py
> +
`No newline at end of file`について調べ、修正をお願いします。

2021-07-15 05:03 UTC, fumiharun11 commented on user/models.py
> +class Follow(models.Model):
モデルClassが追加されているけど、こちらはこのPR内に含む必要はありますか？
必要であればmigrationファイルの生成まで含めるようにし、不要であれば次回PRに含めるようにしてください。

2021-07-15 06:31 UTC, kunikida007 commented on user/test.py
> +
setting.jsonから"files.insertFinalNewline": trueと入力させて頂きました。

2021-07-15 06:38 UTC, kunikida007 commented on user/models.py
> +class Follow(models.Model):
今回は不要なので消去させて頂きました。

2021-07-15 06:38 UTC, kunikida007 commented on config/settings.py
> +import os
不要のため消去いたしました。

2021-07-15 06:48 UTC, fumiharun11 commented on user/test.py
> +
EOFについてエラーがまだ出ているので、最後の不要な空行を削除してから保存してみてもらえますか？

2021-07-15 07:21 UTC, fumiharun11 reviewed
全体的に良いと思います:+1:
一点、`main`ブランチに対してコンフリクトが発生しています。
`main`ブランチに対して直接コミットがpushされたLogがあるので、それが原因かと思われます。
コンフリクト状態ではマージが出来ないため、対応をお願いします！

2021-07-29 02:40 UTC, fumiharun11 approved these changes
LGTM
![LGTM](https://media.giphy.com/media/QyrysGo7Hz70I/giphy.gif)

2021-07-29 02:40 UTC, merged