ツイート機能
kunikida007/tw pull request #2
Opened 2021-07-31 13:05 UTC by kunikida007

ツイート機能になります。
宜しくお願い致します。

2021-08-01 04:15 UTC, s-nakajima2 commented on twiter/urls.py
> +     path('post/',views.tweet, name='post-create'),
ここは周りに合わせて`_`にした方が良いです
```suggestion
     path('post/',views.tweet, name='post_create'),
```

2021-08-04 04:32 UTC, Shunsuke-Shimura commented on q
> +* [33m7e58604[m first commit
余計なファイルが含まれてます

2021-08-04 04:34 UTC, Shunsuke-Shimura commented
いくつか余計なファイルが含まれているようなので、いらないものは削除し、必要ではあるがリポジトリにアップしないものは.gitignoreに追記してください。

2021-08-11 07:03 UTC, fumiharun11 requested changes
コメントしました

2021-08-11 07:03 UTC, fumiharun11 commented on twiter/tests.py
> +        response = self.client.post(reverse('twiter:post-create'), {'content': 'ツイートはリストに表示されるか？'})
`response2`のみ必要？

2021-08-16 08:17 UTC, fumiharun11 commented on twiter/models.py
> +    def perms_user(self, user):
メソッド名だけ見ても何のpermsか分からないので明示しましょう

2021-08-16 08:17 UTC, fumiharun11 commented on user/migrations/0002_delete_follow.py
> +# Generated by Django 3.2.3 on 2021-07-31 08:47
このマイグレーションファイルは何用？

2021-08-16 13:18 UTC, kunikida007 commented on user/migrations/0002_delete_follow.py
> +# Generated by Django 3.2.3 on 2021-07-31 08:47
フォロー機能作成時に使用したマイグレーションファイルを消去し忘れていました。

2021-08-16 13:18 UTC, kunikida007 commented on twiter/models.py
> +    def perms_user(self, user):
畏まりました

2021-08-16 13:29 UTC, fumiharun11 approved these changes
LGTM

2021-08-16 13:29 UTC, merged